language: python

python:
  - "3.6"
  
before_script:
  - pip install -r requirements.txt
  - psql -c 'create database pur_beurre;' -U postgres
  - python3 manage.py collectstatic


env: DJANGO_SETTINGS_MODULE="pur_beurre.settings"

services:
  - postgresql

script:
  - python3 manage.py test
